sonar.projectKey=lets-travel
sonar.projectName=Lets-Travel Management System
sonar.sources=microservices,frontend/travel-admin/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/*.spec.ts,**/jenkins_home/**,**/ansible/**,**/coverage/**,**/src/test/**
sonar.java.binaries=**/target/classes
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/travel-admin/coverage/**/lcov.info
sonar.typescript.tsconfigPath=frontend/travel-admin/tsconfig.sonar.json
sonar.scm.disabled=true

sonar.project.tags=travel,elasticsearch,neo4j

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S1438
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.ts
