sonar.projectKey=travel
sonar.projectName=Travel Management System
sonar.sources=microservices,frontend/travel-admin/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/*.spec.ts,**/jenkins_home/**,**/ansible/**,**/coverage/**,**/src/test/**
sonar.java.binaries=**/target/classes
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/travel-admin/coverage/**/lcov.info
sonar.typescript.tsconfigPath=frontend/travel-admin/tsconfig.sonar.json
sonar.scm.disabled=true
